sudo: false
language: ruby
addons:
  code_climate:
    repo_token: 5ba7d6723270d118185043e817715b7bea4002877c9bffea3ce317bd54d5a1a8
rvm:
- 2.3
- 2.4
- ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head

before_install:
- gem install bundle
install:
- bundle install
script:
- bundle exec rspec
